name: dotnet test

on:
    pull_request:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
    dotnet:
        name: C# Lint
        runs-on: ubuntu-24.04

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup .NET Core SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 9.0.x

            -   name: Check formatting
                run: dotnet format --verify-no-changes
                working-directory: ../

            -   name: Build
                run: dotnet build --configuration Release --no-restore
                working-directory: ./

            -   name: Test
                run: dotnet test Handball.Tests
                working-directory: ./
